sudo: required
services:
  - docker

before_install:
  - docker build -t bcusto/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bcusto/docker-react CI=true npm run test -- --coverage
